name: Build Kernel

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/luxun4/bsp-vermeer-t-oss
          # kernel-dir 不填写，表示在仓库根目录编译
          defconfig: gki_defconfig
          config: kalama_le_gki.fragment
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r383902
          android-version: 12
          ksu: true
          ksu-version: main
          disable-lto: true
          anykernel3: true

      - name: Debug List Source Tree
        run: ls -al && ls -al arch/arm64/configs || true
