name: Build Kernel

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/luxun4/bsp-vermeer-t-oss
          kernel-dir: kernel-source
          kernel-branch: main
          config: gki_defconfig
          arch: arm64
          android-version: 12
          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r383902
          ksu: true
          ksu-version: main
          disable-lto: true
          anykernel3: true
